---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop jenkins-app
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm jenkins-app
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi jenkins-app-img
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t jenkins-app-img .

#    - name: Push Image to dockerhub
#      command: docker push triple3a/comingsoon-page

    - name: run container
      command: docker run -d --name jenkins-app -p 5000:80 jenkins-app-img

